#!/bin/bash

# Required because if sites/default/files is created (by volume mounting perhaps)
# then `ddev drupal install` fails.`

## Description: Reset Drupal ready to install.
## Usage: reset
## Example: "ddev reset"

ddev exec chmod 775 sites/default sites/default/settings.php
ddev exec rm -rf sites/default/files
ddev exec rm -f sites/default/settings.php
